apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  annotations:
    meta.helm.sh/release-name: kube-prometheus-stack
    meta.helm.sh/release-namespace: prometheus
  creationTimestamp: "2023-05-12T02:21:11Z"
  generation: 2
  labels:
    app: kube-prometheus-stack-prometheus
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 45.27.2
    chart: kube-prometheus-stack-45.27.2
    heritage: Helm
    release: kube-prometheus-stack
  name: kube-prometheus-stack-prometheus
  namespace: prometheus
  resourceVersion: "317407"
  uid: 15b5a26b-7bc5-43ce-8c67-f42aa5e6314b
spec:
  alerting:
    alertmanagers:
      - apiVersion: v2
        name: kube-prometheus-stack-alertmanager
        namespace: prometheus
        pathPrefix: /
        port: http-web
  enableAdminAPI: true
  evaluationInterval: 3s
  externalUrl: http://kube-prometheus-stack-prometheus.prometheus:9090
  hostNetwork: false
  image: quay.io/prometheus/prometheus:v2.42.0
  listenLocal: false
  logFormat: logfmt
  logLevel: info
  paused: false
  podMonitorNamespaceSelector: {}
  podMonitorSelector:
    matchLabels:
      release: kube-prometheus-stack
  portName: http-web
  probeNamespaceSelector: {}
  probeSelector:
    matchLabels:
      release: kube-prometheus-stack
  replicas: 1
  retention: 10d
  routePrefix: /
  ruleNamespaceSelector: {}
  ruleSelector:
    matchLabels:
      release: kube-prometheus-stack
  scrapeInterval: 30s
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: kube-prometheus-stack-prometheus
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector:
    matchLabels:
      release: kube-prometheus-stack
  shards: 1
  tsdb:
    outOfOrderTimeWindow: 0s
  version: v2.42.0
  walCompression: true
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: "2023-06-11T13:52:41Z"
      observedGeneration: 2
      status: "True"
      type: Available
    - lastTransitionTime: "2023-06-11T13:52:41Z"
      observedGeneration: 2
      status: "True"
      type: Reconciled
  paused: false
  replicas: 1
  shardStatuses:
    - availableReplicas: 1
      replicas: 1
      shardID: "0"
      unavailableReplicas: 0
      updatedReplicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1
